name: htsimaging
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.5
  - imagemagick
pip:
  - argh
  - statsmodels
  - trackpy==0.4.2
  - scikit-image
  - numba
  - pims
  - tensorflow==1.5
  - pandas==0.25.3
  - rohan
  - keras

