name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.5
  - pip:
    - argh                                               
    - argparse
    - cv2
    - glob
    - json
    - logging
    - multiprocessing
    - #nd2reader
    - pickle
    - pims
    - pims_nd2
    - pimsviewer
    - rohan
    - #setuptools
    - skimage
    - statsmodels
    - string
    - subprocess
    - trackpy=0.4.1
    - yaml